FROM python:3.10-slim

WORKDIR /app

COPY raw_data/ ./raw_data/

WORKDIR /app/api

# Copier les fichiers nécessaires
COPY requirements.txt .
COPY tests_unitaires/ ./tests_unitaires/
COPY main.py .
COPY endpoint/ ./endpoint/
COPY data/ ./data/
COPY utils/ ./utils/
COPY static/ ./static/

# Installer les dépendances
RUN apt-get update && apt-get install -y build-essential
RUN pip install -r requirements.txt
RUN pip install pytest pytest-cov

# Variables d'environnement pour les tests
ENV PYTHONPATH=/app
ENV MLFLOW_TRACKING_URI=http://fake-mlflow:5000

# Ajouter une commande de nettoyage du cache python avant les tests
CMD PYTHONPATH=/app pytest -vv tests_unitaires/